---
- name: Updates sftd on Ubuntu
  hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  - name: wait until the lock file is removed
    wait_for:
      path: /var/lib/dpkg/lock-frontend
      state: absent
    become: yes
    become_user: root
    become_method: sudo
  - name: Install latest sftd
    apt:
      name: scaleft-server-tools
      state: latest
    become: yes
    become_user: root
    become_method: sudo
